### ISSUE TITLE
Convertation error during sending the order

### ISSUE THREAD

**Issue by loki-dv** [bitx/bitx-ruby#7]
Hello!
I have an error during sending order:
Traceback (most recent call last):
```
	1: from 3_orders_buy.rb:93:in `<main>'
/usr/local/rvm/gems/ruby-2.5.1/gems/bitx-0.2.2/lib/private_api.rb:30:in `post_order': undefined method `to_d' for 0.0018:Float (NoMethodError)
Did you mean?  to_c
               to_f
               to_r
               to_i
               to_s
```
I call this function like this:
```
BitX.post_order('BID', (volume*2).round(4), (corner_price*0.95).round(2), ENV['TICKER'])
```
Where volume is float, corner price is float.
Also, I have a bigdecimal in my app and this gem are installed.
What can I do here?
Thank you.

**Comment by loki-dv** [comment]
Sorry, I found a solution:
```
require 'bigdecimal'
require 'bigdecimal/util'
```
(was only `require 'bigdecimal'`)
